require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

def all_pods
  config = use_native_modules!
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/../.."
  )

  pod 'react-native-notifications', :path => '../../'
end

target 'NotificationsExampleApp' do
  all_pods
end

target 'NotificationsExampleAppTests' do
  all_pods
  pod 'OCMock'
end

post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
